### ISSUE TITLE
Run-time issue in tFileExcelSheetInput

### ISSUE THREAD

**Issue by Volo7** [jlolling/talendcomp_tFileExcel#22]
After migration from 6.4.1 to 7.3.1 I got the error below. Please suggest how to fix this issue.

Exception in component tFileInputExcel_1 (jobWH_IBEX_Map)
java.io.IOException: org/apache/commons/compress/utils/InputStreamStatistics
	at org.apache.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:351)
	at org.apache.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:314)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:302)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:271)
	at marketdata.jobwh_ibex_map_1_0.jobWH_IBEX_Map.tFileList_1Process(jobWH_IBEX_Map.java:1521)
	at marketdata.jobwh_ibex_map_1_0.jobWH_IBEX_Map.tFileExist_1Process(jobWH_IBEX_Map.java:741)
	at marketdata.jobwh_ibex_map_1_0.jobWH_IBEX_Map.runJobInTOS(jobWH_IBEX_Map.java:9513)
	at marketdata.jobwh_ibex_map_1_0.jobWH_IBEX_Map.main(jobWH_IBEX_Map.java:9268)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/InputStreamStatistics
	at org.apache.poi.openxml4j.util.ZipArchiveThresholdInputStream.<init>(ZipArchiveThresholdInputStream.java:63)
	at org.apache.poi.openxml4j.util.ZipSecureFile.getInputStream(ZipSecureFile.java:147)
	at org.apache.poi.openxml4j.util.ZipSecureFile.getInputStream(ZipSecureFile.java:34)
	at org.apache.poi.openxml4j.util.ZipFileZipEntrySource.getInputStream(ZipFileZipEntrySource.java:66)
	at org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:260)
	at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:726)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:274)
	at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:339)
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.InputStreamStatistics
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more

**Comment by jlolling** [comment]
Hi, this issue comes from a tFileArchive or tFileUnarchive component in your job.
Both components uses are very out-dated library (common-compress-1.8) which is incompatible with the library version used for the current apache-poi api (used in my components).
To prevent that, I have added clones of both archive components in the distribution of the excel components. tFileArchive2 and tFileUnarchive2 which are working in exactly the same way like the original components but using the current version of commons-compress library.

**Comment by Volo7** [comment]
Hi Jan,
The strange thing that in my job I do not use tFileArchive or tFileUnarchive components at all.
I am using tFileExist, tFileList, tHashOutput, tForeach, tMap, tFileExcelWorkbookOpen, tFileSheetOutput, tFileExcelWorkbookSave.
So, I am not sure which component breaks my job. What common-compress library do you use in your components?
Best Regards,
Volodymyr

**Comment by jlolling** [comment]
OK, strange. Could you deactivate one by one of the other components until the error disappears? It would be important to know which causes the problem. 
I use the commons-compress version 1.19 (dependency of the apache-poi lib).

**Comment by Volo7** [comment]
Ok, I found this component. When I deactivate tFileExcelWorkbookOpen - tFileExcelSheetInput works fine.
I am confused because tFileExcelWorkbookOpen is part of tFileExcel package...

**Comment by jlolling** [comment]
This is quite clear. The tFileExcelWorkbookOpen carries all the libs. 
I have tested the new components in Talend Open Studio 7.3.1 and does not found any issues (except the problems with the archive components).
Is there a child job or is your job a child job?

**Comment by Volo7** [comment]
Usually, I use this job as a child job. But now I am running it as a standalone job. My version is Talend Cloud Big Data (7.3.1.20200219_1130).

**Comment by jlolling** [comment]
Ok, a job without anything else than the tFileExcel components (without also the build-in excel components) must work! Could you check that please?

**Comment by Volo7** [comment]
Ok, I fixed it! 
This post gave me some ideas: https://community.talend.com/t5/Design-and-Development/tFileExcel-component-error-when-using-tFileArchive-in-the-same/td-p/198427
The problem was with tFileExcelWorkbookOpen. In the Modules view for tFileExcelWorkbookOpen was Maven URI=mvn:org.talend.libraries/commons-compress-1.19/6.0.0-SNAPSHOT/jar. But it should be mvn:org.apache.commons/commons-compress/1.19/jar (this one I found for tFileInputExcel). 
The same issue I see for tFileUnachive2. For some reason for this component the link is mvn:org.talend.libraries/commons-compress-1.19/6.1.0/jar...

**Comment by Volo7** [comment]
Thank you for the quick response and great components that you built!

**Comment by jlolling** [comment]
Did you told me recently you do not habe the tFileArchive component in your job?

**Comment by jlolling** [comment]
The way I have included the lib commons-compress to the component is the strange Talend way. It was not my decision or idea to do so.

**Comment by Volo7** [comment]
Yes, I do not have. But you can see all components in the Modules even if you do not have it in your job.

**Comment by Volo7** [comment]
![image](https://user-images.githubusercontent.com/19478666/78840159-07d45f00-79c8-11ea-88c8-9a6a59965fec.png)

**Comment by Volo7** [comment]
You can see on my screenshot what I fixed manually in the Modules View

**Comment by Volo7** [comment]
Maybe it gives you some ideas. Thank you again!

**Comment by jlolling** [comment]
Interesting. I will update my components. I was not aware the normal Maven way is no possible, This must be an new feature of Talend 7.

**Comment by Volo7** [comment]
Ok, Thanks!
